version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint"
