version: '3.8'
services:
  server:
    build:
      context: .
    environment:
      REDIS_URL: redis://redis
    tmpfs: /tmp
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:7-alpine
    volumes:
    - redis-storage:/data
    restart: always

volumes:
  redis-storage: {}
